# Generated by Django 4.1.6 on 2023-03-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_remove_university_id_alter_university_mail_ratting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
        migrations.AddField(
            model_name='question',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvote', to='userApp.user'),
        ),
        migrations.AddField(
            model_name='question',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvote', to='userApp.user'),
        ),
        migrations.DeleteModel(
            name='Ratting',
        ),
    ]
