# Generated by Django 4.1.6 on 2023-03-26 11:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_remove_question_votes_question_downvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='detailed_question',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='simple', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('downvotes', models.ManyToManyField(blank=True, related_name='answer_downvote', to='userApp.user')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.question')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='answer_upvote', to='userApp.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.user')),
            ],
        ),
    ]
